packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  core-js: true
  argon2: true
  esbuild: true
  msw: true
  tesseract.js: true

onlyBuiltDependencies:
  - argon2
  - core-js
  - esbuild
  - msw

ignorePnpmScripts: false
