import {
  Activity,
  Banknote,
  CalendarClock,
  CalendarDays,
  CircleDollarSign,
  ClipboardCheck,
  CreditCard,
  LayoutGrid,
  ListChecks,
  RefreshCcw,
  Sparkles,
  UsersRound,
  UtensilsCrossed,
  WalletCards,
  type LucideIcon,
} from "lucide-react";
import type {
  DashboardWidgetDefinition,
  DashboardWidgetDefinitionId,
  DashboardWidgetSize,
  DashboardWidgetSizePreset,
} from "./dashboardWidgetTypes";

const sizes: Record<DashboardWidgetSizePreset, DashboardWidgetSize> = {
  small: { preset: "small", w: 3, h: 3, minW: 3, minH: 3, maxW: 4, maxH: 4 },
  wide: { preset: "wide", w: 6, h: 3, minW: 4, minH: 3, maxW: 12, maxH: 4 },
  medium: { preset: "medium", w: 4, h: 6, minW: 3, minH: 5, maxW: 8, maxH: 10 },
  large: { preset: "large", w: 6, h: 8, minW: 4, minH: 6, maxW: 12, maxH: 12 },
  fullWidth: { preset: "fullWidth", w: 12, h: 6, minW: 8, minH: 5, maxW: 12, maxH: 12 },
  doubleHeight: { preset: "doubleHeight", w: 4, h: 12, minW: 3, minH: 8, maxW: 8, maxH: 18 },
  custom: { preset: "custom", w: 4, h: 6, minW: 3, minH: 3, maxW: 12, maxH: 18 },
};

export const DASHBOARD_WIDGET_SIZES = sizes;

export const DASHBOARD_WIDGET_DEFINITIONS: DashboardWidgetDefinition[] = [
  {
    id: "activePatients",
    version: 1,
    name: "Pacientes activos",
    description: "Total de pacientes activos en la sucursal.",
    category: "patients",
    kind: "kpi",
    iconKey: "users",
    tone: "green",
    defaultSize: sizes.small,
    allowedSizes: ["small", "wide"],
    singleton: true,
    configurable: true,
    requiredModule: "patients",
  },
  {
    id: "newPatientsThisMonth",
    version: 1,
    name: "Nuevos pacientes del mes",
    description: "Altas registradas durante el mes actual.",
    category: "patients",
    kind: "kpi",
    iconKey: "sparkles",
    tone: "cyan",
    defaultSize: sizes.small,
    allowedSizes: ["small", "wide"],
    singleton: true,
    configurable: true,
    requiredModule: "patients",
  },
  {
    id: "consultationsToday",
    version: 1,
    name: "Consultas de hoy",
    description: "Consultas realizadas y citas previstas para hoy.",
    category: "consultations",
    kind: "kpi",
    iconKey: "calendar",
    tone: "blue",
    defaultSize: sizes.small,
    allowedSizes: ["small", "wide"],
    singleton: true,
    configurable: true,
    requiredModule: "consultations",
  },
  {
    id: "consultationsThisMonth",
    version: 1,
    name: "Consultas del mes",
    description: "Consultas completadas durante el mes actual.",
    category: "consultations",
    kind: "kpi",
    iconKey: "clipboard",
    tone: "purple",
    defaultSize: sizes.small,
    allowedSizes: ["small", "wide"],
    singleton: true,
    configurable: true,
    requiredModule: "consultations",
  },
  {
    id: "incomeThisMonth",
    version: 1,
    name: "Ingresos del mes",
    description: "Importe cobrado durante el mes actual.",
    category: "finance",
    kind: "kpi",
    iconKey: "money",
    tone: "purple",
    defaultSize: sizes.small,
    allowedSizes: ["small", "wide"],
    singleton: true,
    configurable: true,
    requiredModule: "billing",
  },
  {
    id: "pendingPayments",
    version: 1,
    name: "Saldo pendiente",
    description: "Saldo total pendiente de cobro.",
    category: "payments",
    kind: "kpi",
    iconKey: "wallet",
    tone: "orange",
    defaultSize: sizes.small,
    allowedSizes: ["small", "wide"],
    singleton: true,
    configurable: true,
    requiredModule: "billing",
  },
  {
    id: "activePlans",
    version: 1,
    name: "Planes activos",
    description: "Planes nutricionales activos de pacientes vigentes.",
    category: "plans",
    kind: "kpi",
    iconKey: "mealPlan",
    tone: "green",
    defaultSize: sizes.small,
    allowedSizes: ["small", "wide"],
    singleton: true,
    configurable: true,
    requiredModule: "mealplan",
  },
  {
    id: "pendingSync",
    version: 1,
    name: "Pendientes de sincronizar",
    description: "Cambios locales que aún requieren sincronización.",
    category: "system",
    kind: "kpi",
    iconKey: "sync",
    tone: "slate",
    defaultSize: sizes.small,
    allowedSizes: ["small", "wide"],
    singleton: true,
    configurable: false,
  },
  {
    id: "upcomingConsultations",
    version: 3,
    name: "Próximas consultas",
    description: "Agenda inmediata y próximas atenciones.",
    category: "agenda",
    kind: "upcomingConsultations",
    iconKey: "calendarClock",
    tone: "blue",
    defaultSize: { ...sizes.large, preset: "medium", w: 4, minW: 3, minH: 7 },
    allowedSizes: ["medium", "large", "fullWidth"],
    singleton: true,
    configurable: true,
    requiredModule: "agenda",
  },
  {
    id: "weeklyActivity",
    version: 3,
    name: "Actividad semanal",
    description: "Comparación de consultas y pacientes nuevos.",
    category: "activity",
    kind: "weeklyActivity",
    iconKey: "activity",
    tone: "purple",
    defaultSize: { ...sizes.large, w: 5, minW: 3, minH: 7 },
    allowedSizes: ["large", "fullWidth"],
    singleton: true,
    configurable: true,
  },
  {
    id: "alerts",
    version: 2,
    name: "Alertas y pendientes",
    description: "Cobros, citas y planes que requieren atención.",
    category: "alerts",
    kind: "alerts",
    iconKey: "alerts",
    tone: "orange",
    defaultSize: { ...sizes.large, preset: "medium", w: 3, minW: 3, minH: 7 },
    allowedSizes: ["medium", "large", "fullWidth"],
    singleton: true,
    configurable: true,
  },
  {
    id: "financialSummary",
    version: 2,
    name: "Resumen financiero",
    description: "Ingresos, saldo y avance de cobranza.",
    category: "finance",
    kind: "financialSummary",
    iconKey: "banknote",
    tone: "green",
    defaultSize: { ...sizes.medium, w: 5, minW: 3, minH: 6 },
    allowedSizes: ["medium", "large", "fullWidth"],
    singleton: true,
    configurable: true,
    requiredModule: "billing",
  },
  {
    id: "recentPayments",
    version: 3,
    name: "Pagos recientes",
    description: "Últimos cobros registrados en consultas.",
    category: "payments",
    kind: "recentPayments",
    iconKey: "card",
    tone: "cyan",
    defaultSize: { ...sizes.medium, minW: 3 },
    allowedSizes: ["medium", "large", "fullWidth"],
    singleton: true,
    configurable: true,
    requiredModule: "billing",
  },
  {
    id: "quickActions",
    version: 2,
    name: "Accesos rápidos",
    description: "Atajos a las tareas más frecuentes.",
    category: "quickActions",
    kind: "quickActions",
    iconKey: "grid",
    tone: "blue",
    defaultSize: { ...sizes.medium, w: 3, minH: 6 },
    allowedSizes: ["medium", "large", "fullWidth"],
    singleton: true,
    configurable: true,
  },
  {
    id: "customKpi",
    version: 1,
    name: "KPI personalizado",
    description: "Métrica creada con una fuente y un cálculo permitido.",
    category: "custom",
    kind: "customKpi",
    iconKey: "sparkles",
    tone: "purple",
    defaultSize: sizes.small,
    allowedSizes: ["small", "wide"],
    singleton: false,
    configurable: true,
  },
];

export const DASHBOARD_WIDGET_DEFINITION_BY_ID = new Map(
  DASHBOARD_WIDGET_DEFINITIONS.map((definition) => [definition.id, definition]),
);

export const DASHBOARD_WIDGET_ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  alerts: ListChecks,
  banknote: Banknote,
  calendar: CalendarDays,
  calendarClock: CalendarClock,
  card: CreditCard,
  clipboard: ClipboardCheck,
  grid: LayoutGrid,
  mealPlan: UtensilsCrossed,
  money: CircleDollarSign,
  sparkles: Sparkles,
  sync: RefreshCcw,
  users: UsersRound,
  wallet: WalletCards,
};

export function getDashboardWidgetDefinition(
  id: DashboardWidgetDefinitionId,
): DashboardWidgetDefinition {
  return DASHBOARD_WIDGET_DEFINITION_BY_ID.get(id) ?? DASHBOARD_WIDGET_DEFINITION_BY_ID.get("customKpi")!;
}

export function getDashboardWidgetSize(
  definitionId: DashboardWidgetDefinitionId,
  preset: DashboardWidgetSizePreset,
): DashboardWidgetSize {
  const definition = getDashboardWidgetDefinition(definitionId);
  if (!definition.allowedSizes.includes(preset)) return definition.defaultSize;
  if (preset === definition.defaultSize.preset) return definition.defaultSize;
  const size = sizes[preset];
  if (definition.kind === "kpi" || definition.kind === "customKpi") return size;
  const minimumHeight = definition.defaultSize.h;
  return {
    ...size,
    h: Math.max(size.h, minimumHeight),
    minH: Math.max(size.minH, definition.defaultSize.minH),
    maxH: Math.max(size.maxH ?? minimumHeight, minimumHeight),
  };
}
